### ISSUE TITLE
install Kerbrute sys/cdefs.h: No such file or directory

### ISSUE THREAD

**Issue by mennobo** [IppSec/parrot-build#42]
Got this error when installing on virtualbox on Arch (Running amd). 
![Image](https://github.com/user-attachments/assets/3a41d83e-c25e-4cf2-b22d-461eb8c57e39)

Fix, as per [StackOverflow](https://askubuntu.com/questions/470796/fatal-error-sys-cdefs-h-no-such-file-or-directory)
run: `sudo apt-get --reinstall install libc6 libc6-dev`

I'll look into making a PR.

**Comment by mennobo** [comment]
Changing `kerbrute.yaml` to this fixes the issue.

```yaml
---
- name: Check if /usr/include/x86_64-linux-gnu/sys is present
  stat:
    path: /usr/include/x86_64-linux-gnu/sys
  register: sys_dir

- name: Reinstall of libc6 libc6-dev by command.
  command: "apt --reinstall install libc6 libc6-dev"
  when: not sys_dir.stat.exists

- name: Install Kerbrute
  shell: go install github.com/ropnop/kerbrute@master

```
