### ISSUE TITLE
community.general.pipx missing

### ISSUE THREAD

**Issue by MierBen** [IppSec/parrot-build#8]
Hello.

While I tried to use your ansible script to configure my parrot, I ran into the problem with missing community.general collection for pipx. 
I'll recommend to add this collection into the requirements.yml file like:

```
---
roles:
  - src: gantsign.visual-studio-code

collections:
  - name: community.general
    type: galaxy

```

Maybe it's only my problem. Hope, this will be helpful.
